### ISSUE TITLE
Using dask_awkward.to_dask_array results in odd behavior for dask.array operations

### ISSUE THREAD

**Issue by lgray** [dask-contrib/dask-awkward#177] opened 2023-03-03 17:54 UTC
Using latest-in-PyPI `dask_awkward` and `uproot`:

```python3
import uproot
import numpy as np
import dask.array as da
import dask_awkward as dak

x = uproot.dask({"https://github.com/CoffeaTeam/coffea/blob/master/tests/samples/nano_dy.root?raw=true": "Events"})
y = dak.to_dask_array(dak.any(x.Muon_pt > 30, axis=1))
z = da.zeros_like(y, dtype=np.uint32)

print(z.compute())
```

results in:

```
<function _broadcast_trick_inner at 0x11a6f9b20>
```

Which is a confusing outcome!

**Comment by douglasdavis** [comment] 2023-03-06 17:30
writing out what I've found so far:

It looks like this may be coming from the fact that `y` has unknown shape/partitioning.

With this diff

```diff
diff --git a/src/dask_awkward/lib/io/io.py b/src/dask_awkward/lib/io/io.py
index ba27fe2..cbbf8e1 100644
--- a/src/dask_awkward/lib/io/io.py
+++ b/src/dask_awkward/lib/io/io.py
@@ -276,7 +276,11 @@ def to_dask_array(array: Array, optimize_graph: bool = True) -> DaskArray:
         new = map_partitions(ak.to_numpy, array, meta=empty_typetracer())
         graph = new.dask
         dtype = primitive_to_dtype(array._meta.layout.form.type.primitive)
-        chunks: tuple[tuple[float, ...], ...] = ((np.nan,) * array.npartitions,)
+        if array.known_divisions:
+            divs = np.array(array.divisions)
+            chunks = (tuple(divs[1:] - divs[:-1]),)
+        else:
+            chunks: tuple[tuple[float, ...], ...] = ((np.nan,) * array.npartitions,)
         return new_da_object(
             graph,
             new.name,
```

And writing

```python
x = uproot.dask({"https://github.com/CoffeaTeam/coffea/blob/master/tests/samples/nano_dy.root?raw=true": "Events"})
a = dak.any(x.Muon_pt > 30, axis=1)
y = dak.to_dask_array(a)
y.eager_compute_divisions()
z = da.zeros_like(y, dtype=np.uint32)

print(z.compute())
```

things work as expected.

I need to figure out what minimal information `da.zeros_like` needs and then how to make sure `dak` can provide it.

**Comment by douglasdavis** [comment] 2023-03-06 17:34
I think dask.array needs to raise an exception for unknown chunks to make sure this problem is avoided.

**Comment by lgray** [comment] 2023-03-06 17:40
This is a pretty incredibly severe limitation of using `dask.array` in that case. For some of our datasets determining all the chunks would be incredibly slow (just opening 2k files is slow). I'm surprised there's no late-binding way to do this in `dask.array`.

hmm.

**Comment by douglasdavis** [comment] 2023-03-06 17:46
Yea I'm going to take a look at the implementation in dask.array to see if there's any possibility for being compatible with unknown chunks.

**Comment by douglasdavis** [comment] 2023-03-06 17:52
I'm thinking we might have to leverage delayed to get something to work as intended

**Comment by douglasdavis** [comment] 2023-03-06 19:57
Or we can use map_partitions

```python
In [12]: import uproot
    ...: import numpy as np
    ...: import dask.array as da
    ...: import dask_awkward as dak
    ...: 
    ...: x = uproot.dask(
    ...:     {
    ...:         "/Users/ddavis/software/repos/coffea/tests/samples/nano_dy.root": "Events",
    ...:     }
    ...: )

In [13]: dak.map_partitions(
    ...:     lambda a, dt: np.zeros_like(ak.to_numpy(a), dtype=np.uint32),
    ...:     y,
    ...:     np.uint32,
    ...:     meta=dak.core.empty_typetracer(),
    ...: ).to_dask_array(dtype=np.uint32, optimize_graph=False).compute()
Out[13]: 
array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=uint32)
```
(used optimize_graph=False because the lambda doesn't support typetracers; it could of course be a function that has built in support for typetracers)

the code above works with this patch


```patch
diff --git a/src/dask_awkward/lib/core.py b/src/dask_awkward/lib/core.py
index bfd3e44..2083c33 100644
--- a/src/dask_awkward/lib/core.py
+++ b/src/dask_awkward/lib/core.py
@@ -1102,10 +1102,10 @@ class Array(DaskMethodsMixin, NDArrayOperatorsMixin):
 
         return to_delayed(self, optimize_graph=optimize_graph)
 
-    def to_dask_array(self, optimize_graph: bool = True) -> DaskArray:
+    def to_dask_array(self, dtype: Any = None, optimize_graph: bool = True) -> DaskArray:
         from dask_awkward.lib.io.io import to_dask_array
 
-        return to_dask_array(self, optimize_graph=optimize_graph)
+        return to_dask_array(self, dtype=dtype, optimize_graph=optimize_graph)
 
     def to_parquet(
         self,
diff --git a/src/dask_awkward/lib/io/io.py b/src/dask_awkward/lib/io/io.py
index cbbf8e1..ce10872 100644
--- a/src/dask_awkward/lib/io/io.py
+++ b/src/dask_awkward/lib/io/io.py
@@ -231,7 +231,7 @@ def to_dask_bag(array: Array) -> DaskBag:
     return Bag(array.dask, array.name, array.npartitions)
 
 
-def to_dask_array(array: Array, optimize_graph: bool = True) -> DaskArray:
+def to_dask_array(array: Array, dtype: Any = None, optimize_graph: bool = True) -> DaskArray:
     """Convert awkward array collection to a Dask array collection.
 
     This conversion requires the awkward array to have a rectilinear
@@ -275,7 +275,7 @@ def to_dask_array(array: Array, optimize_graph: bool = True) -> DaskArray:
     if ndim == 1:
         new = map_partitions(ak.to_numpy, array, meta=empty_typetracer())
         graph = new.dask
-        dtype = primitive_to_dtype(array._meta.layout.form.type.primitive)
+        dtype = dtype or primitive_to_dtype(array._meta.layout.form.type.primitive)
         if array.known_divisions:
             divs = np.array(array.divisions)
             chunks = (tuple(divs[1:] - divs[:-1]),)
@@ -296,7 +296,7 @@ def to_dask_array(array: Array, optimize_graph: bool = True) -> DaskArray:
         while no_primitive:
             content = content.content
             no_primitive = not hasattr(content, "primitive")
-        dtype = primitive_to_dtype(content.primitive)
+        dtype = dtype or primitive_to_dtype(content.primitive)
 
         name = f"to-dask-array-{tokenize(array)}"
         nan_tuples_innerdims = ((np.nan,),) * (ndim - 1)
```

**Comment by lgray** [comment] 2023-03-06 20:34
This solution could work in my case (but not generally). Can you make a PR so I can pull a branch locally?

**Comment by douglasdavis** [comment] 2023-03-22 19:01
Closed by https://github.com/dask/dask/pull/10064

**Closed by douglasdavis** 2023-03-22 19:01 UTC
