### ISSUE TITLE
Segfault on compute() when loading specific columns in from_parquet.

### ISSUE THREAD

**Issue by riga** [dask-contrib/dask-awkward#140] opened 2023-01-08 15:10 UTC
Hi!

I really appreciate the feature to load only specific, arbitrarily nested columns from a parquet file 🎉 This really boosts our IO.

However, I spotted a case where calling `compute()` on a `dak` array results in a segfault, depending on which exact columns were passed to `from_parquet()`. You can find a test snippet and an example input file at [this gist](https://gist.github.com/riga/6e04cae06d65cb78f17ae625d83de0b0), but the short story is the following.

If a file contains some nested columns, say

```
array
├─ Jet
│  ├─ pt
│  ├─ mass
│  └─ ... (others!)
└─ ... (others)
```

and I load all columns under "Jet" via `from_parquet(file, columns=["Jet.*"])` everything works as expected. But as soon as I load only a *subset of columns* under "Jet" such as `from_parquet(file, columns=["Jet.pt"])`, `compute()` causes a segfault.

I repeated this on different files to make sure none of them was corrupted, but the error occurred consistently.

- Python 3.10.8
- dask_awkward 2023.1.0
- awkward 2.0.5

**Comment by douglasdavis** [comment] 2023-01-09 19:52
Hi @riga, thanks for raising the issue with the minimal reproducer! We'll start digging around

**Comment by martindurant** [comment] 2023-01-09 20:00
@douglasdavis , are you working on this? I suspect it's a mismatch with those .list.item. column name bits that parquet has.

**Comment by martindurant** [comment] 2023-01-09 20:21
The following test passed
```python
def test_nested_columns(tmpdir):
    tmpdir = str(tmpdir)
    data = [
        {
            "Jet": {
                "pt": 0,
                "mass": 1,
            }
        },
        {
            "Jet": {
                "pt": 1,
                "mass": 2,
            }
        },
    ]
    arr = dak.from_awkward(ak.from_iter(data), 2)
    to_parquet(arr, tmpdir)
    arr1 = dak.from_parquet(tmpdir)
    arr2 = dak.from_parquet(tmpdir, columns=["Jet.*"])
    assert_eq(arr1, arr2)
    arr2 = dak.from_parquet(tmpdir, columns=["Jet.pt"])
    assert "mass" not in arr2.Jet.fields
    assert arr2.Jet.pt.compute().tolist() == [0, 1]
```

Looking at the gist example next.

**Comment by martindurant** [comment] 2023-01-09 20:30
@jpivarski , a segfault should not happen ever, right?
I am seeing segfault with bare ak even with a field that is not variable-length, no "item" names. This even loads successfully in fastparquet
```
ak.from_parquet("calib.parquet", columns=['MET.pt_tec_jet_dm1_down'])
```

 Also, I suggest that trying to load a column that doesn't exist should raise an error - currently you get an array of the right number of elements but containing no daya
```
<Array [{}, {}, {}, {}, {}, {}, ..., {}, {}, {}, {}, {}, {}] type='18000 * {}'>
```

**Comment by jpivarski** [comment] 2023-01-10 17:54
Sure, we don't like segfaults, but there are some cases in which pyarrow raises them. The JIRA ticket that @agoose77 pointed to might be* this example, but @riga would have to recreate the Parquet file with `extensionarray=False` (see [ak.to_parquet](https://awkward-array.org/doc/main/reference/generated/ak.to_parquet.html)) to be sure.

\*Edit: it is. See below.

I tracked down the line that it's failing on—this one:

https://github.com/scikit-hep/awkward/blob/6d4de4c3d902159ad3a1ce864d5f39218f94ffa8/src/awkward/operations/ak_from_parquet.py#L300

But I could only reproduce the segfault in vivo. When I tried to reproduce (what looks like) all relevant steps outside of the Awkward codebase, there was no segfault:

```python
>>> import pyarrow.parquet
>>> import fsspec.parquet
>>> fs, _, paths = fsspec.get_fs_token_paths("calib.parquet", mode="rb", storage_options=None)
>>> with fs.open("calib.parquet") as file_for_metadata:
...     parquetfile_for_metadata = pyarrow.parquet.ParquetFile(file_for_metadata)
... 
>>> with fs.open("/home/jpivarski/irishep/awkward/calib.parquet", "rb") as file:
...     parquetfile = pyarrow.parquet.ParquetFile(file)
...     arrow_table = parquetfile.read("MET.pt_tec_jet_dm1_down")
... 
>>> arrow_table
pyarrow.Table

----
```

No segfault, but also no data. An odd thing about this file is that it can't find the column with a dotted name like `"MET.pt_tec_jet_dm1_down"`.

```python
>>> import pyarrow.parquet
>>> pyarrow.parquet.read_table("calib.parquet", columns=["MET.pt_tec_jet_dm1_down"])
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/jpivarski/mambaforge/lib/python3.9/site-packages/pyarrow/parquet/__init__.py", line 2827, in read_table
    return dataset.read(columns=columns, use_threads=use_threads,
  File "/home/jpivarski/mambaforge/lib/python3.9/site-packages/pyarrow/parquet/__init__.py", line 2473, in read
    table = self._dataset.to_table(
  File "pyarrow/_dataset.pyx", line 331, in pyarrow._dataset.Dataset.to_table
  File "pyarrow/_dataset.pyx", line 298, in pyarrow._dataset.Dataset.scanner
  File "pyarrow/_dataset.pyx", line 2356, in pyarrow._dataset.Scanner.from_dataset
  File "pyarrow/_dataset.pyx", line 2202, in pyarrow._dataset._populate_builder
  File "pyarrow/error.pxi", line 100, in pyarrow.lib.check_status
pyarrow.lib.ArrowInvalid: No match for FieldRef.Name(MET.pt_tec_jet_dm1_down) in # ...
# (all columns are listed with names like "Jet" and "MET", not deep columns)
deterministic_seed: uint64 not null
mc_weight: float not null
__fragment_index: int32
__batch_index: int32
__last_in_fragment: bool
__filename: string

>>> pyarrow.parquet.read_table("calib.parquet", columns=["pt_tec_jet_dm1_down"])
# ... same error message

>>> pyarrow.parquet.read_table("calib.parquet", columns=["MET"])
# this works, but it returns a table with all columns within the "MET" StructArray
```

The weird thing is that this column is in the schema, and it has the right `path`:

```python
>>> import pyarrow.parquet
>>> file = pyarrow.parquet.ParquetFile("calib.parquet")
>>> file.metadata.schema.names.index("pt_tec_jet_dm1_down")
95
>>> file.metadata.schema.column(95)
<ParquetColumnSchema>
  name: pt_tec_jet_dm1_down
  path: MET.pt_tec_jet_dm1_down
  max_definition_level: 0
  max_repetition_level: 0
  physical_type: FLOAT
  logical_type: None
  converted_type (legacy): NONE
```

-----------

The more I look at this, the more it looks like the bug @agoose77 referred to, above. That one had a minimal reproducer, let me see if it has the same properties as this one.

It does! First, it lists column names and paths the same way (see the JIRA ticket: `"one"` and `"two"` are nested within a `"column"` StructArray):

```python
>>> pq.ParquetFile("record.parquet").metadata.schema.column(0)
<ParquetColumnSchema>
  name: one
  path: column.one
  max_definition_level: 1
  max_repetition_level: 0
  physical_type: INT64
  logical_type: None
  converted_type (legacy): NONE
>>> pq.ParquetFile("record.parquet").metadata.schema.column(1)
<ParquetColumnSchema>
  name: two
  path: column.two
  max_definition_level: 1
  max_repetition_level: 0
  physical_type: DOUBLE
  logical_type: None
  converted_type (legacy): NONE
```

But also, if we comment out our ExtensionArray registration (something that we can only do temporarily, as a test):

https://github.com/scikit-hep/awkward/blob/6d4de4c3d902159ad3a1ce864d5f39218f94ffa8/src/awkward/_connect/pyarrow.py#L170-L172

the segfault goes away:

```python
>>> import awkward as ak
>>> array = ak.from_parquet("calib.parquet", columns=["MET.pt_tec_jet_dm1_down"])
>>> array.type.show()
18000 * {
    MET: {
        pt_tec_jet_dm1_down: float32
    }
}
```

I'm already pretty certain this is a real-world instance of [ARROW-17539](https://issues.apache.org/jira/browse/ARROW-17539), though if @riga recreates the file with `extensionarray=False` and can read it back in unmodified Awkward, that would make it certain. It's also a work-around until the pyarrow bug gets fixed.

Meanwhile, I'll post an update in JIRA with the fact that we ran into this in a real-world case.

**Comment by riga** [comment] 2023-01-11 09:05
Thanks for the super quick debugging!

Indeed, @jpivarski, when created with `extensionarray=False` there's no segfault and the array contains what I would expect.

I get a different error though downstream in our code base (`IndexedArray cannot contain a union-type (unless categorical), option-type, or indexed 'content' (IndexedOptionArray); try IndexedArray.simplified instead` when I do a `ak.concatenate` on parts of the resulting array) that I need to disentangle first, but reading the docs for the `extensionarray` setting, I guess such things are to be expected when the type is not fully preserved.

For debugging purposes, I uploaded the file [here](https://cernbox.cern.ch/remote.php/dav/public-files/xQTpSqrvZQSSTZp/calib_no_extensionarray.parquet) and also update the [gist](https://gist.github.com/riga/6e04cae06d65cb78f17ae625d83de0b0).

**Comment by riga** [comment] 2023-01-11 10:40
@agoose77 I updated the comment above with what I believe is the root cause of the error I see. If I "cast" the computed array via `ak.fill_none(ak_array, -999)` to a non-optional type, then the subsequent `ak.concatenate` works fine.

**Comment by riga** [comment] 2023-01-11 10:53
You're too fast ;) I added it above.

**Comment by riga** [comment] 2023-01-11 16:47
~~The file is [here](https://cernbox.cern.ch/remote.php/dav/public-files/tNcTlCBIFOzmeur/arrays.pickle), but reading it in a minimal reproducer and doing the concat works unfortunately :D~~

---

Ok, it took me a while but I managed to create a minimal, failing example. It requires loading 2 arrays and applying one selection mask each.

```shell
wget https://cernbox.cern.ch/remote.php/dav/public-files/yZhLyUjTDaVKLVQ/arrays.tgz
tar -xzf arrays.tgz
# -> 4 parquet files: 2 arrays and 2 selection masks
```

```python
import awkward as ak

arrays = []
for i in range(1, 3):  # index 2 leads to the "bad" file
    arr = ak.from_parquet(f"array_{i}.parquet")
    sel = ak.from_parquet(f"sel_{i}.parquet")
    arrays.append(arr[sel])

ak.concatenate(arrays, axis=1)
```

Just to be sure: the files above are the result of loading the actual files with selected columns in `dak.from_parquet`. When I don't pass any columns there, everything works. The files for the case are [here](https://cernbox.cern.ch/remote.php/dav/public-files/PKXFJCtlEruxUVz/arrays_allcols.tgz), just in case.

**Comment by riga** [comment] 2023-01-11 18:51
Great, thank you!

**Comment by douglasdavis** [comment] 2023-01-11 18:55
Catching up on the conversation here-- am I correct in thinking this can be closed as an issue here in dask-awkward?

**Comment by jpivarski** [comment] 2023-01-11 19:11
For Awkward, we should wait for the pyarrow issue to be fixed. (If we try to identify it and raise a RuntimeError, we'll have to remove that extra code later.)

**Comment by douglasdavis** [comment] 2023-01-11 19:17
Sounds good!

**Closed by douglasdavis** 2023-01-11 19:17 UTC
