### ISSUE TITLE
Calling `len` on attribute of nanoevents fails

### ISSUE THREAD

**Issue by iasonkrom** [dask-contrib/dask-awkward#300] opened 2023-06-26 13:42 UTC
The following snippet fails:
```python
from coffea.nanoevents import NanoAODSchema, NanoEventsFactory
import os

fname = "coffea/tests/samples/nano_dy.root"
events = NanoEventsFactory.from_root(
    {os.path.abspath(fname): "Events"},
    schemaclass=NanoAODSchema,
    metadata={"dataset": "DYJets"},
    permit_dask=True,
).events()

print(len(events.Electron))
```
with
```
FieldNotFoundError: no field 'Electron' in record with 1 fields

This error occurred while attempting to slice

    repr-raised-AttributeError

with

    'Electron'
```
Calling `len` on just `events` works fine.

**Comment by iasonkrom** [comment] 2023-06-26 15:06
Even slicing just fails
```python
from coffea.nanoevents import NanoAODSchema, NanoEventsFactory
import os

fname = "coffea/tests/samples/nano_dy.root"
events = NanoEventsFactory.from_root(
    {os.path.abspath(fname): "Events"},
    schemaclass=NanoAODSchema,
    metadata={"dataset": "DYJets"},
    permit_dask=True,
).events()

events.Electron[:20]
```

**Comment by jpivarski** [comment] 2023-06-26 18:48
Based on the error message, I think the issue is

```python
events.Electron
```

itself. I don't think it even gets to the part where it would apply `len` or the slice.

Specifically, the error message is saying that the `"Electron"` field is not in the record array. What names do exist?

```python
ak.fields(events)  # <-- what is this list?
```

**Comment by iasonkrom** [comment] 2023-06-26 23:11
Electron is actually in fields. It's weird if you look at the screenshots.
<img width="997" alt="image" src="https://github.com/dask-contrib/dask-awkward/assets/82155404/c09c5085-9f62-4eda-b5ef-ce47d9ec7a42">
<img width="610" alt="image" src="https://github.com/dask-contrib/dask-awkward/assets/82155404/68caec98-6f90-4c24-9fc6-18ba70fdf516">
Calling `len` on `events` before calling `len` on `events.Electron` fixes it

**Comment by iasonkrom** [comment] 2023-06-26 23:12
<img width="678" alt="image" src="https://github.com/dask-contrib/dask-awkward/assets/82155404/08e057d0-0625-4f80-a75e-c88c60d330af">
<img width="1386" alt="image" src="https://github.com/dask-contrib/dask-awkward/assets/82155404/93ac21a3-d897-4794-929a-2e7d6ecc5b44">

Same thing with slicing

**Comment by jpivarski** [comment] 2023-06-26 23:22
It sounds like there's a mismatch between two sets of metadata, though this is all happening on the head-node side (errors happen _before_ `.compute()`). I don't understand it because I had thought that a `dak.Array` had only one set of metadata, the `_meta` object, which is an Awkward type-tracer.

@douglasdavis, is there any point where two sets of metadata come into play?

**Comment by agoose77** [comment] 2023-06-27 00:49
`AwkwardInputLayer.project_columns` is being called with `columns=[]`, which leads to `columns = self._meta.fields[:1]` taking place, i.e. the first column is arbitrarily chosen. 

I think this is happening because the length computed for `calculate_known_divisions` is passing in `meta` as `empty_typetracer`, meaning that we lose track of what was required to compute this column.

I am guessing that `calculate_known_divisions` needs to do something that's more scalar aware here, e.g. `partitionwise_layer`

**Comment by agoose77** [comment] 2023-06-27 01:03
The problem is that `compute_known_divisions` is not correctly marking `Electron` as required. The outermost `ListOffsetArray.length` only touches the shape (of `offsets`), not data. 

It's too late in the day for me to figure out what we want to happen here. I also note that we might need to rework this to not use `map_partitions`, or conversely, to have `map_partitions` become scalar aware.

**Comment by douglasdavis** [comment] 2023-06-27 15:18
There are a few moving targets here:

1. @agoose77 pointed out what I'd call the "main" issue here: `compute_known_divisions` is failing because it actually calls `compute()` and the compute is failing because behind the scenes `ak.num` is getting used and the optimization procedure is dropping the `Electron` field as unnecessary. I'm thinking form rehydration should have fixed this- we need to get the `unproject_layout` implementation into uproot.
2. The reason things work if `len(events)` is called before `len(events.Electron)` is because the behind-the-scenes `compute()` that happens when calling `len(events)` is running successfully in that case, and then we cache the known divisions in the `_divisions` attribute of the `events` collection; so, when accessing the `Electrons` field now, asking for len on `events.Electrons` just returns `events.Electrons.divisions[-1]` (and divisions are conserved on simple field access) instead of needing to compute the divisions (slicing failing on `events.Electrons[...]` is also related to this).
3. Shouldn't uproot be reporting known divisions now? this would bypass the issue completely

What it boils all boils down to is whether or not the divisions are known before trying to access a field and then asking for length. `len(events)` is the same as `len(events.Electrons)`, but `len(events.Electrons)` _if divisions are not known_ is going to fail because the typetracer only optimization graph is optimizing away the unnecessary field.

> I also note that we might need to rework this to not use map_partitions, or conversely, to have map_partitions become scalar aware.

To compute known divisions there's a special map_partitions call happening that is manually scalar aware by passing in an empty typetracer array here:
https://github.com/dask-contrib/dask-awkward/blob/7619d9719f3bdacb69b14d0324b6d6f057b39171/src/dask_awkward/lib/core.py#L1847-L1855

**Comment by agoose77** [comment] 2023-06-27 15:49
@douglasdavis Gah! :facepalm: 

I thought we'd merged https://github.com/scikit-hep/uproot5/pull/900 into uproot5, but it transpires that I closed it without merging. Perhaps I confused your PR into my PR (though I was aware of that at one point). 

This is another example of where `touch_data` and `touch_shape` need to be handled properly; `ak.num` doesn't touch any data, so we just `touch_shape` of the offsets. As dask-awkward doesn't handle this part of the report, no columns are reported, so we load the first one. That isn't guaranteed to have the same length as `Electron`.

**Comment by douglasdavis** [comment] 2023-06-27 17:28
> so we load the first one. That isn't guaranteed to have the same length as Electron.

Ah there are cases where one field in a record array can have a different len than another field?

**Comment by douglasdavis** [comment] 2023-06-27 17:29
Also this has me thinking we need to put some thought into using the touch_shape part of the report

**Comment by douglasdavis** [comment] 2023-07-06 18:03
This should be taken care with https://github.com/scikit-hep/uproot5/pull/900 getting merged in uproot

**Closed by douglasdavis** 2023-07-06 18:03 UTC
